version: '3.8'

services:
  front:
    volumes:
      - type: bind
        source: ./
        target: /app
    build:
      context: ./frontend/
    command: bash -c "cd app/frontend && trunk serve --release --address 0.0.0.0 --port=8181"
    ports:
       - "80:8181"
    environment:
      - HOST_IP=${HOST_IP}

  back:
    volumes:
      - type: bind
        source: ./
        target: /app
    build:
      context: ./backend/
    command: bash -c "cd app/backend && cargo run --release 0.0.0.0"
    ports:
      - "3030:3030"
      - "7878:7878"

